CREATE TABLE TB_INFO(
INFO_NO NUMBER(3) NOT NULL,
PC_NO VARCHAR2(10) UNIQUE NOT NULL,
NM VARCHAR2(20),
EMAIL VARCHAR2(50),
HOBBY VARCHAR2(1000),
MBTI VARCHAR2(4)
);
DESC TB_INFO;
DROP TABLE TB_INFO;

SELECT nm, mbti FROM tb_info
WHERE mbti IN('INTP', 'ENFP');


